scr_initenemy();

grav = 0.5;
hsp = 0;
vsp = 0;
movespeed = 0
state = states.walk
stunned = 0
alarm[0] = 150
roaming = true
collectdrop = 5
flying = false
straightthrow = false
cigar = false
cigarcreate = false
stomped = false
shot = false
thrown = false
reset = false
hp = 3
hitboxcreate = false
grounded = true
bombreset = 0
idlespr = spr_trash
stunfallspr = spr_trash_bump
walkspr =spr_trash
grabbedspr = spr_trash_bump
scaredspr = spr_trash_bump
image_xscale = -1
flash = false
slapped = false
birdcreated = false
boundbox = false
points = false
important = false
spr_dead = spr_trash_dead
heavy = true
depth =0