thrown = false
grabbed = false
hsp = 0
vsp = 0 
grav = 0.5
flash = true
hp = 0
grounded = true
state = 0
playerid = obj_player1
image_speed = 0
image_index = random_range(0, image_number -1)
mask_index = spr_player_mask
depth = -5
stuntouchbuffer = 0