event_inherited();

grav = 0.5;
hsp = 0;
vsp = 0;
movespeed = 1
state = states.walk
stunned = 0
alarm[0] = 150
roaming = true
collectdrop = 5
flying = false
straightthrow = false
cigar = false
cigarcreate = false
stomped = false
shot = false
thrown = false
reset = false
hp = 3
hitboxcreate = false
grounded = true
chargereset = 0
idlespr = spr_peasanto_idle
stunfallspr = spr_peasanto_stun
walkspr =spr_peasanto_walk
grabbedspr = spr_peasanto_stun
scaredspr = spr_peasanto_stun
image_xscale = -1
flash = false
slapped = false
birdcreated = false
boundbox = false
angry = false
spr_dead = spr_peasanto_dead
important = false
heavy = false
depth =0

sprite_index = walkspr